# Generated by Django 3.0.3 on 2022-01-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('by', models.CharField(blank=True, max_length=64)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('by', models.CharField(blank=True, max_length=64)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('descendants', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
