# Generated by Django 3.0.3 on 2022-02-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('by', models.CharField(blank=True, max_length=64)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('parent', models.IntegerField()),
                ('text', models.TextField(blank=True)),
                ('kids', models.ManyToManyField(blank=True, related_name='comments', to='newsyapp.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='kids',
            field=models.ManyToManyField(blank=True, related_name='stories', to='newsyapp.Comment'),
        ),
    ]
