# Generated by Django 3.2.11 on 2022-02-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsyapp', '0002_auto_20220203_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
